### ISSUE TITLE
Question about occlusion map of sceneflow

### ISSUE THREAD

**Issue by LeeyqSenSe** [mli0603/stereo-transformer#10]
Hi, thanks for your great work. I have a question about occlusion map label. You mentioned that computing occluded area can be found in dataset/preprocess.py. However, with this file, we can only get occlusion region on image border, but the occlusion map provided in sample data of sceneflow seems not.  Thank you very much for your help!

**Comment by mli0603** [comment]
Hi @LeeyqSenSe,

The code for finding occlusion in both image border and object border is [here](https://github.com/mli0603/stereo-transformer/blob/main/utilities/misc.py#L69). I use this as an offline processing step, therefore the code is not in dataset/preprocess.py.

**Comment by LeeyqSenSe** [comment]
Thanks for your reply.  Got it.
