### ISSUE TITLE
STTR-light inference

### ISSUE THREAD

**Issue by lebionick** [mli0603/stereo-transformer#12]
I want to try new light version of this network, but as far as I understand there is no inference script example for now? And training is not parametrized so that I can get "light" version just by changing script arguments?
So to run this model I need to train with `pretrain.sh` (`main.py` with default parameters) and later use code from `inference_example.ipynb` with these default values?

**Comment by mli0603** [comment]
Oh i have completely forgot this. The default parameters are in the `main.py` (which is different from the `main.py` in main branch), so you should be able to run `pretrain.sh` directly. 

But inference example code should be slightly different. When I find time I will write one up. If you are ahead of me, feel free to create a pull request or share it here ;)

**Comment by lebionick** [comment]
Ok, I'll try :)

**Comment by lebionick** [comment]
Done: #13 please check ;)

**Comment by mli0603** [comment]
I'll check over the weekend. Thank you very much!

**Comment by mli0603** [comment]
Just merged. Thank you!
