### ISSUE TITLE
self-attention visualization

### ISSUE THREAD

**Issue by DaoyiG** [mli0603/stereo-transformer#14]
Hi!

Good works! Do you mind providing the code or details about how to implement the visualization of the self-attention map?

Thanks!

**Comment by mli0603** [comment]
Hi @DaoyiG, sure, I will. Please give me sometime to clean it up if you don't mind?

**Comment by DaoyiG** [comment]
> Hi @DaoyiG, sure, I will. Please give me sometime to clean it up if you don't mind?

Sure, thanks!

**Comment by mli0603** [comment]
Instead of creating a pull request, I've decided just to put the code here, so I don't have to merge branches and etc. And I confess I did the minmal cleanup :p 

```python
import torch
import os
import matplotlib.pyplot as plt
import numpy as np
from dataset.preprocess import denormalize
from scipy.ndimage import gaussian_filter
import math


def pdf(x, mu=0.0, sigma=1.0):
    x = (x - mu) / sigma
    return np.exp(-x * x / 2.0) / math.sqrt(2.0 * math.pi) / sigma


def convert_attn_to_heatmap(epipolar_line_attn):
    distance = np.abs(np.arange(0, h).reshape(h, 1) - np.ones([1, w]) * row) / h * 80  # HxW
    distance = pdf(distance)
    heatmap = distance * epipolar_line_attn.numpy()
    heatmap = gaussian_filter(heatmap, sigma=1.5)
    heatmap = heatmap / heatmap.max()

    return heatmap


directory = 'PATH_TO_DATA'
row = int(182 / 3)
col = int(586 / 3)

left = denormalize(np.load(os.path.join(directory, 'left.npy'))[:, 1::3, 1::3])
right = denormalize(np.load(os.path.join(directory, 'right.npy'))[:, 1::3, 1::3])
target = torch.load(os.path.join(directory, 'target.dat')).cpu().numpy()[0]
h, w, _ = left.shape

# %% self attention
for i in range(6):
    self_attn = torch.load(os.path.join(directory, 'self_attn_' + str(i) + '.dat'))[row].cpu()

    plt.figure(figsize=(8, 6))
    plt.imshow(self_attn, cmap='gray')
    plt.axis('off')
    plt.savefig('self_attn_map_' + str(i) + '.png')
    plt.show()

    epipolar_line_attn = self_attn[col]
    heatmap = convert_attn_to_heatmap(epipolar_line_attn)
    overlay = 0.8 * left + heatmap[..., None].repeat(3, -1) * 4

    plt.figure(figsize=(8, 6))
    plt.imshow(overlay)
    plt.plot(col, row, 'r+', markersize=24, markeredgewidth=3)
    plt.axis('off')
    plt.tight_layout()
    plt.text(-2, -4, 'Layer %d' % i, fontsize=20)
    plt.savefig('self_attn_' + str(i) + '.png')
    plt.show()

# %% cross attention
for i in range(6):
    if i == 5:
        cross_attn = torch.load(os.path.join(directory, 'attn_weight.dat'))[row].cpu()
        cross_attn = cross_attn[:-1, :-1]
    else:
        cross_attn = torch.load(os.path.join(directory, 'cross_attn_' + str(i) + '.dat'))[row].cpu()

    plt.figure(figsize=(8, 6))
    plt.imshow(cross_attn, cmap='gray')
    plt.axis('off')
    plt.savefig('cross_attn_map_' + str(i) + '.png')
    plt.show()

    epipolar_line_attn = cross_attn[col]
    heatmap = convert_attn_to_heatmap(epipolar_line_attn)
    overlay = 0.8 * right + heatmap[..., None].repeat(3, -1) * 4

    plt.figure(figsize=(8, 6))
    plt.imshow(overlay)
    plt.plot(target[row, col, 0], row, 'b+', markersize=24, markeredgewidth=3)
    plt.axis('off')
    plt.tight_layout()
    plt.text(-2, -4, 'Layer %d' % i, fontsize=20)
    plt.savefig('cross_attn_' + str(i) + '.png')
    plt.show()
```

**Comment by DaoyiG** [comment]
Thanks a lot!

**Comment by Bayrambai** [comment]
Hi, thanks for sharing your visualization code. What are these target.dat, self_attn_i.dat files? Are these self-cross attention maps, if yes how can I obtain them?
Thanks

**Comment by Bayrambai** [comment]
> Instead of creating a pull request, I've decided just to put the code here, so I don't have to merge branches and etc. And I confess I did the minmal cleanup :p
> 
> ```python
> import torch
> import os
> import matplotlib.pyplot as plt
> import numpy as np
> from dataset.preprocess import denormalize
> from scipy.ndimage import gaussian_filter
> import math
> 
> 
> def pdf(x, mu=0.0, sigma=1.0):
>     x = (x - mu) / sigma
>     return np.exp(-x * x / 2.0) / math.sqrt(2.0 * math.pi) / sigma
> 
> 
> def convert_attn_to_heatmap(epipolar_line_attn):
>     distance = np.abs(np.arange(0, h).reshape(h, 1) - np.ones([1, w]) * row) / h * 80  # HxW
>     distance = pdf(distance)
>     heatmap = distance * epipolar_line_attn.numpy()
>     heatmap = gaussian_filter(heatmap, sigma=1.5)
>     heatmap = heatmap / heatmap.max()
> 
>     return heatmap
> 
> 
> directory = 'PATH_TO_DATA'
> 
> # row and col of interest
> row = int(182 / 3)
> col = int(586 / 3)
> 
> # downsample images
> left = denormalize(np.load(os.path.join(directory, 'left.npy'))[:, 1::3, 1::3])
> right = denormalize(np.load(os.path.join(directory, 'right.npy'))[:, 1::3, 1::3])
> target = torch.load(os.path.join(directory, 'target.dat')).cpu().numpy()[0]
> h, w, _ = left.shape
> 
> # %% self attention
> for i in range(6):
>     self_attn = torch.load(os.path.join(directory, 'self_attn_' + str(i) + '.dat'))[row].cpu()
> 
>     plt.figure(figsize=(8, 6))
>     plt.imshow(self_attn, cmap='gray')
>     plt.axis('off')
>     plt.savefig('self_attn_map_' + str(i) + '.png')
>     plt.show()
> 
>     epipolar_line_attn = self_attn[col]
>     heatmap = convert_attn_to_heatmap(epipolar_line_attn)
>     overlay = 0.8 * left + heatmap[..., None].repeat(3, -1) * 4
> 
>     plt.figure(figsize=(8, 6))
>     plt.imshow(overlay)
>     plt.plot(col, row, 'r+', markersize=24, markeredgewidth=3)
>     plt.axis('off')
>     plt.tight_layout()
>     plt.text(-2, -4, 'Layer %d' % i, fontsize=20)
>     plt.savefig('self_attn_' + str(i) + '.png')
>     plt.show()
> 
> # %% cross attention
> for i in range(6):
>     if i == 5:
>         cross_attn = torch.load(os.path.join(directory, 'attn_weight.dat'))[row].cpu()
>         cross_attn = cross_attn[:-1, :-1]
>     else:
>         cross_attn = torch.load(os.path.join(directory, 'cross_attn_' + str(i) + '.dat'))[row].cpu()
> 
>     plt.figure(figsize=(8, 6))
>     plt.imshow(cross_attn, cmap='gray')
>     plt.axis('off')
>     plt.savefig('cross_attn_map_' + str(i) + '.png')
>     plt.show()
> 
>     epipolar_line_attn = cross_attn[col]
>     heatmap = convert_attn_to_heatmap(epipolar_line_attn)
>     overlay = 0.8 * right + heatmap[..., None].repeat(3, -1) * 4
> 
>     plt.figure(figsize=(8, 6))
>     plt.imshow(overlay)
>     plt.plot(target[row, col, 0], row, 'b+', markersize=24, markeredgewidth=3)
>     plt.axis('off')
>     plt.tight_layout()
>     plt.text(-2, -4, 'Layer %d' % i, fontsize=20)
>     plt.savefig('cross_attn_' + str(i) + '.png')
>     plt.show()
> ```

Hi, thanks for sharing your visualization code. What are these target.dat, self_attn_i.dat files? Are these self-cross attention maps, if yes how can I obtain them?
Thanks

**Comment by mli0603** [comment]
Hi @Bayrambai
you can just save the attn after each layer of cross and self attention by ‘torch.save’

**Comment by Bayrambai** [comment]
Thanks for your reply, I am curious what is the size of the loaded atten (Wx2HxC)? since it is being used in 'plt.imshow' which has to be supported with a proper array shape. Do you apply any feature reduction method such as PCA as you already mentioned in the repo?
Thanks

**Comment by mli0603** [comment]
@Bayrambai 
The size of **attn weight** (**not** the features) is `Wx2Hx1`, where `C=1`.

You can direclty visualize the attn weight without any dimentionality reduction techniques.

**Comment by Bayrambai** [comment]
Sorry, still got a little bit of confusion here, you already have commented line to save feats and attns_weights, however the size of attn weighs are `2HxWxW` after self attns and `HxWxW` after cross. I would appreciate it if you could help me to clarify this confusion.

**Comment by mli0603** [comment]
Hi @Bayrambai 

- the self attention has size `2H` because there is one for left image and there is one for right image. The first `HxWxW` is for left image and the second `HxWxW` is for right image.
- the cross attention has size `H` because there is only one cross attention, either left->right or right->left.
- the selection of row/col is for attention stride to reduce the memory. I am not sure what your question is, can you clarify?
-
