### ISSUE TITLE
sttr_light_kitti_finetuned_model.pth.tar

### ISSUE THREAD

**Issue by emepetres** [mli0603/stereo-transformer#15]
Hi @mli0603 , first of all great work!

I'd like to run the inference on the kitti finetuned model. To do that I guess I have to finetune the _sttr_light_sceneflow_pretrained_model_, but I'm having problems installing nvidia apex.

Could you please, If you have it, publish __sttr_light_kitti_finetuned_model.pth.tar__ as well so I can test the inference on the kitti dataset directly?

BTW I'm creating a docker image and a inference script that I expect to share via PR when I manage to fix the nvidia apex issue.

Thanks!

**Comment by mli0603** [comment]
Hi @emepetres , I haven't got time to fine-tune the light version on KITTI yet. I planned to do it, but to be honest I have too much on my plate now and I confess I am behind...

I would really appreciate the docker image if you can share ;) Thank you! 
There is already a inference script proposed on this PR #13 . Maybe you can check too to see if it runs on your end?

**Comment by mli0603** [comment]
I have merged #13 already!
