### ISSUE TITLE
How much cuda memory is needed to train?

### ISSUE THREAD

**Issue by Leviosaaaa** [mli0603/stereo-transformer#16]
Hi! Thank you for sharing such great work!
My question is how much cuda memory is needed for training. I read that you used a single Titan RTX GPU to train in your paper; does that mean this network needs 24G GPU to train with a batch size of 1?
Thanks~

**Comment by mli0603** [comment]
Hi @Leviosaaaa, sorry I must have missed this!

No of course not! Based on my `nvidia-smi` output the requirement is 8GB if you train on Sceneflow with the default setting. If you run into memory constraint situation, there are couple of ways to do it:
- Set the random crop size to a smaller number [here](https://github.com/mli0603/stereo-transformer/blob/main/dataset/scene_flow.py#L146)
- Set the attention stride rate higher [here](https://github.com/mli0603/stereo-transformer/blob/main/main.py#L50)
- Or use the most recent released STTR-light [here](https://github.com/mli0603/stereo-transformer/tree/sttr-light)

Let me know if you still have questions ;)

**Comment by Leviosaaaa** [comment]
Thank you!
