### ISSUE TITLE
Pretrain model:sttr_light_sceneflow_pretrained_model.pth.tar

### ISSUE THREAD

**Issue by fromWRF** [mli0603/stereo-transformer#20]
Hi,
When I used the pre-trained model: sttr_light_sceneflow_pretrained_model.pth.tar, it told as follows:

RuntimeError: Error(s) in loading state_dict for STTR:
	Missing key(s) in state_dict: "tokenizer.up.2.convTrans.0.weight", "tokenizer.up.2.convTrans.1.weight", "tokenizer.up.2.convTrans.1.bias", "tokenizer.up.2.convTrans.1.running_mean", "tokenizer.up.2.convTrans.1.running_var", "tokenizer.up.2.convTrans.1.num_batches_tracked", "tokenizer.up.2.convTrans.2.weight", "tokenizer.up.2.convTrans.2.bias", "tokenizer.dense_block.2.double_conv.0.weight", "tokenizer.dense_block.2.double_conv.1.weight", "tokenizer.dense_block.2.double_conv.1.bias", "tokenizer.dense_block.2.double_conv.1.running_mean", "tokenizer.dense_block.2.double_conv.1.running_var", "tokenizer.dense_block.2.double_conv.1.num_batches_tracked", "tokenizer.dense_block.2.double_conv.3.weight", "tokenizer.dense_block.2.double_conv.4.weight", "tokenizer.dense_block.2.double_conv.4.bias", "tokenizer.dense_block.2.double_conv.4.running_mean", "tokenizer.dense_block.2.double_conv.4.running_var", "tokenizer.dense_block.2.double_conv.4.num_batches_tracked". 
	size mismatch for tokenizer.bottle_neck.denselayer1.conv1.weight: copying a param with shape torch.Size([64, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([16, 128, 1, 1]).
	size mismatch for tokenizer.bottle_neck.denselayer1.norm2.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for tokenizer.bottle_neck.denselayer1.norm2.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for tokenizer.bottle_neck.denselayer1.norm2.running_mean: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for tokenizer.bottle_neck.denselayer1.norm2.running_var: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for tokenizer.bottle_neck.denselayer1.conv2.weight: copying a param with shape torch.Size([16, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([4, 16, 3, 3]).
	size mismatch for tokenizer.bottle_neck.denselayer2.norm1.weight: copying a param with shape torch.Size([144]) from checkpoint, the shape in current model is torch.Size([132]).
	size mismatch for tokenizer.bottle_neck.denselayer2.norm1.bias: copying a param with shape torch.Size([144]) from checkpoint, the shape in current model is torch.Size([132]).
	size mismatch for tokenizer.bottle_neck.denselayer2.norm1.running_mean: copying a param with shape torch.Size([144]) from checkpoint, the shape in current model is torch.Size([132]).
	size mismatch for tokenizer.bottle_neck.denselayer2.norm1.running_var: copying a param with shape torch.Size([144]) from checkpoint, the shape in current model is torch.Size([132]).
	size mismatch for tokenizer.bottle_neck.denselayer2.conv1.weight: copying a param with shape torch.Size([64, 144, 1, 1]) from checkpoint, the shape in current model is torch.Size([16, 132, 1, 1]).
	size mismatch for tokenizer.bottle_neck.denselayer2.norm2.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for tokenizer.bottle_neck.denselayer2.norm2.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for tokenizer.bottle_neck.denselayer2.norm2.running_mean: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for tokenizer.bottle_neck.denselayer2.norm2.running_var: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for tokenizer.bottle_neck.denselayer2.conv2.weight: copying a param with shape torch.Size([16, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([4, 16, 3, 3]).
	size mismatch for tokenizer.bottle_neck.denselayer3.norm1.weight: copying a param with shape torch.Size([160]) from checkpoint, the shape in current model is torch.Size([136]).
	size mismatch for tokenizer.bottle_neck.denselayer3.norm1.bias: copying a param with shape torch.Size([160]) from checkpoint, the shape in current model is torch.Size([136]).
	size mismatch for tokenizer.bottle_neck.denselayer3.norm1.running_mean: copying a param with shape torch.Size([160]) from checkpoint, the shape in current model is torch.Size([136]).
	size mismatch for tokenizer.bottle_neck.denselayer3.norm1.running_var: copying a param with shape torch.Size([160]) from checkpoint, the shape in current model is torch.Size([136]).
	size mismatch for tokenizer.bottle_neck.denselayer3.conv1.weight: copying a param with shape torch.Size([64, 160, 1, 1]) from checkpoint, the shape in current model is torch.Size([16, 136, 1, 1]).
	size mismatch for tokenizer.bottle_neck.denselayer3.norm2.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for tokenizer.bottle_neck.denselayer3.norm2.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for tokenizer.bottle_neck.denselayer3.norm2.running_mean: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for tokenizer.bottle_neck.denselayer3.norm2.running_var: copying a param with shape to

**Comment by mli0603** [comment]
Hi @fromWRF, which branch are you using?

**Comment by Culturenotes** [comment]
How do I use lightweight models? Loading a lightweight model directly will cause an error. How to modify the configuration parameters?

**Comment by Culturenotes** [comment]
> 嗨@fromWRF，您使用的是哪个分支？

How do I use lightweight models? Loading a lightweight model directly will cause an error. How to modify the configuration parameters?

**Comment by mli0603** [comment]
@Culturenotes 

Thanks for reaching out.

You need to
1)  first checkout the sttr-light branch 
2) load the models directly should work.

**Comment by coralexbadea** [comment]
Don't we need the parameters for the sttr-light? In the sttr-light branch only the number of heads is different 4 instead of 6 but still getting the error when loading the pretrained light model.

args.channel_dim = 128
args.position_encoding='sine1d_rel'
args.num_attn_layers=6
args.nheads=4
args.regression_head='ot'
args.context_adjustment_layer='cal'
args.cal_num_blocks=8
args.cal_feat_dim=16
args.cal_expansion_ratio=4

**Comment by mli0603** [comment]
Hi @coralexbadea 

Is this the sttr-light branch?

**Comment by mli0603** [comment]
I updated the `sttr-light` branch and the default parameters should match sttr-light in the `main.py`. I tested everything on my end and not errrors were thrown. I am closing this for now, but if you run into additional errors, feel free to reopen this.
