### ISSUE TITLE
The method in the paper is a great idea, but I have some questions in the process of reading

### ISSUE THREAD

**Issue by davidyang180** [mli0603/stereo-transformer#25]
![image](https://user-images.githubusercontent.com/45596935/117557991-77c18700-b0ab-11eb-8edc-83ca9078a43d.png)

1.In the last cross-attention layer,According to the formula mentioned in the attention, the output of the last cross-attention layer should be the VO weighted matrix map with the size of (IW * IW), so how to use this value map for optimal transport?

2.In the optimal transport algorithm, the paper mentioned "he cost matrix M is set to the negative of the attention computed by the cross-attention module in Equation 2", but the last cross-attention layer attention output is calculated for each pixel feature by splitting the channel dimension of feature descriptors, so which one is used the negative of αh to set the cost matrix?

Thanks!

**Comment by mli0603** [comment]
Hi @davidyang180 

1. You are right about attn output from last cross attn is `IW*IW` for each row of the image, and there are IH rows. We further have dustbins to assign occluded regions (each IW will have one additional cell). This `IH*(IW+1)*(IW+1)` is the input of the optimal transport (ignoring batch size).
2. You are right that attn is split along channel dimension. The final attention used in optimal transport cost matrix is the sum of channel-wise output. Code is here (https://github.com/mli0603/stereo-transformer/blob/main/module/attention.py#L137)
