### ISSUE TITLE
questions about Table 2 in the paper

### ISSUE THREAD

**Issue by jiaw-z** [mli0603/stereo-transformer#29]
Hello, thanks for the good work.
Just about the Generalization without fine-tuning evaluation of PSMNet in Table 2.
In the Table 2, the Middlebury 3 px Error of PSMNet trained on Scene Flow datatest is 12.96, while we got the 21.2, which is far from that reported in your paper. And the pre-trained model from github performances 23.24.
We use the 15 training images of Middlebury from https://vision.middlebury.edu/stereo/submit3/
Do you use a subset of these 15 images or 
10 evaluation training sets with GT or
13 additional datasets with GT from https://vision.middlebury.edu/stereo/data/scenes2014/#description ?
Wondering the reason about it.
Thanks.

**Comment by mli0603** [comment]
Hi @jiaw-z, this is odd. Here are some info I think can clarify things up a little.

- Dataset: I used the 15 training images from Middlebury. And quarter resolution.
- Pretrained weights: I used the one provided by the author, which gives me the 12.96 3px error. I re-trained PSMNet with the same setup but with my augmentation, which gives me 10.24 3px error.
- Evaluation: do you evaluate all pixels of non-occluded only? I evaluated non-occluded only for fair comparison against STTR. This may also make a difference.

**Comment by jiaw-z** [comment]
Problem solved.
It's I evaluate both the occ and noc.
Thanks for your help.
