### ISSUE TITLE
pretrain model

### ISSUE THREAD

**Issue by jmuyjl** [mli0603/stereo-transformer#30]
it seems that I can't download the link of the pre-trained model. I can't download it with the downloader such as Thunder. Could you please put a link of the resource of BaiduYun? Thank you very much.

**Comment by mli0603** [comment]
@jmuyjl

#27 has the same request. I will find a way to upload to BaiduYun in the next few days.

**Comment by jmuyjl** [comment]
@mli0603 Is there a link to update the model? I am so interested in your work, I really want to try it

**Comment by mli0603** [comment]
Link: https://pan.baidu.com/s/1euozEOX3fVdYID3v5dHJ_w 
Password: jvda

Let me know if it doesn't work.

**Comment by jmuyjl** [comment]
@mli0603 Thank you for your reply. I downloaded your compressed package, but still reported an error when decompressing it.

error：not an archive

**Comment by mli0603** [comment]
@jmuyjl 
You don't need to unzip it. You can directly load it.
