### ISSUE TITLE
How to get the dataset SCARED?

### ISSUE THREAD

**Issue by yanzhou-li** [mli0603/stereo-transformer#4]
Dear author:
When I go to the  `Stereo Correspondence and Reconstruction of Endoscopic Data` 's website ,I can't find the download link of dataset. Can you help me?
tks!

**Comment by mli0603** [comment]
Hello!

If you weren’t part of the MICCAI 2019 Challenge, I think you’ll have to contact Intuitive to get the data. You can contact the committee of the challenge about this.

I hope this helps!

**Comment by yanzhou-li** [comment]
All right.I thought the data was open.Maybe I made a mistake.

**Comment by saifsayed** [comment]
Hi @PrinceEAdjei . Can you please share the SCARED dataset. I tried emailing the team at intuitive but they seem to not respond.

**Comment by yanzhou-li** [comment]
你好，李yanzhou已经收到你的邮件，谢谢！

**Comment by PrinceEAdjei** [comment]
Hello,

I will get back to you shortly.

BR
PEAdjei

**Comment by yinyang472** [comment]
您好 方便的话可以分享一下数据集么 我这边有一个实验需要用到这个数据集  十分感谢

**Comment by yanzhou-li** [comment]
你好，李yanzhou已经收到你的邮件，谢谢！

**Comment by yinyang472** [comment]
@PrinceEAdjei   Can you please share the SCARED dataset. I would appreciate it if you can share it.

**Comment by yinyang472** [comment]
@saifsayed have you got the dataset? can you share it? if you can, contact 289475058@qq.com.

**Comment by LucasML1** [comment]
Can you please share the SCARED dataset. If you can, contact me at lu.casoria88@gmail.com.
Thanks.

**Comment by LucasML1** [comment]
Hi @PrinceEAdjei  Can you please share the SCARED dataset. If you can, contact me at lu.casoria88@gmail.com.
Thanks

**Comment by LucasML1** [comment]
Hi @saifsayed  if you have the dataset, you can share it.
This is my e-mail address lu.casoria88@gmail.com
Thanks

**Comment by yinyang472** [comment]
I don't have. i will send it to you if I find it later. if you find it , can you share it with me?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月7日(星期五) 晚上11:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mli0603/stereo-transformer] How to get the dataset SCARED? (#4)





 
Hi @saifsayed  if you have the dataset, you can share it.
 This is my e-mail address ***@***.***
 Thanks

**Comment by ZhouJankin** [comment]
Hi @yanzhou-li ,
Can you share the SCARED dataset with email if you have got it? My address is zhoujankin@gmail.com, and I found it for days. Thanks a lot!

**Comment by suriya-1403** [comment]
Hi @yanzhou-li, Can you provide the SCARED dataset to me through email or Google Drive if you have it? Because I have been working on an endoscopic project and need it very badly, please.

**Comment by yanzhou-li** [comment]
你好，李yanzhou已经收到你的邮件，谢谢！

**Comment by fisherliaoc** [comment]
Hi @yanzhou-li , Could you share the SCARED dataset. I emailed the committee but don't get any respond.
I appreciate if you can share it. Thank you. My email is yuwentuodaren@163.com.

**Comment by CaoDenk** [comment]
@yanzhou-li  你好，你能分享下SCARED 数据集么？我的邮箱1652547656@qq.com  非常感谢

**Comment by yanzhou-li** [comment]
你好，李yanzhou已经收到你的邮件，谢谢！

**Comment by 90duyangwang** [comment]
@yanzhou-li 您好，求分享下SCARED数据集，我的邮箱zhongzhongyuanyuan@gmail.com，感激不尽！

**Comment by Afakenametoo** [comment]
> 
Can you please share the SCARED dataset. I would appreciate it if you can share it.

求分享下SCARED数据集，我的邮箱zhusq815@gmail.com,非常感谢

**Comment by Danture** [comment]
因为下载时需签署协议书不能分享给他人，需要数据集的同学可以去https://endovissub2019-scared.grand-challenge.org/官方网站先注册，然后下载协议书发给负责人就能得到一个下载链接了。

**Comment by cd20000301** [comment]
> Hello,
> 
> Thank you for your work. I recently have access to the SCARED dataset, after contacting the organizers. I am trying to understand your data loader for this dataset but I cannot seem to reconcile the data structure from the files I have downloaded with your code.
> 
> I have datasets 1 - 9, and within each keyframes 1-5. Within each keyframe, there's a 'data' folder with frame_data and scene_points sub-folders. One level up, there is a YAML file, left and right depth maps and then right and left images.
> 
> Are you familiar with this data format?
> 
> Thank

@PrinceEAdjei ,Hi Can you please share the SCARED dataset. If you can, contact me at cd_freya@163.com.
Tks!!!!!!!!

**Comment by yanzhou-li** [comment]
你好，李yanzhou已经收到你的邮件，谢谢！

**Comment by VeroMieites** [comment]
Hello! Is there still a way to get the SCARED dataset? If any of you have it, please contat me at vma494@alumnos.unican.es. Thank you!

**Comment by yangsenchen** [comment]
Hi @yanzhou-li ,
Can you share the SCARED dataset via email if you have got it? My address is [89temple98@gmail.com](mailto:89temple98@gmail.com). Thank you very much!

**Comment by neneyork** [comment]
@yanzhou-li 
Could you please send me the SCARED dataset. I tried to send the challenge rule to Allen, but there is no response. My email is c1019654701@gmail.com. Thank you!

**Comment by yanzhou-li** [comment]
你好，李yanzhou已经收到你的邮件，谢谢！

**Comment by Saadi-AI** [comment]
> Hello,
> 
> Thank you for your work. I recently have access to the SCARED dataset, after contacting the organizers. I am trying to understand your data loader for this dataset but I cannot seem to reconcile the data structure from the files I have downloaded with your code.
> 
> I have datasets 1 - 9, and within each keyframes 1-5. Within each keyframe, there's a 'data' folder with frame_data and scene_points sub-folders. One level up, there is a YAML file, left and right depth maps and then right and left images.
> 
> Are you familiar with this data format?
> 
> Thank

can you share the dataset with me please?

saadkhalil1997@gmail.com

**Comment by yanzhou-li** [comment]
你好，李yanzhou已经收到你的邮件，谢谢！

**Comment by VeroMieites** [comment]
> Hello, 
> 
> Thank you for your work. I recently have access to the SCARED dataset, after contacting the organizers. I am trying to understand your data loader for this dataset but I cannot seem to reconcile the data structure from the files I have downloaded with your code. 
> 
> I have datasets 1 - 9, and within each keyframes 1-5. Within each keyframe, there's a 'data' folder with frame_data and scene_points sub-folders. One level up, there is a YAML file, left and right depth maps and then right and left images. 
> 
> Are you familiar with this data format? 
> 
> Thank
> 
> 
> 
> 

Hi! I was trying to get it by myself but I was unsuccessful. Would you be able to share it with me at vma494@alumnos.unican.es?
Best wishes.

**Comment by slowwaker** [comment]
Hi @yanzhou-li,

Can you send me the link for the SCARED dataset? I need this dataset for my undergraduate project.
My email is lawrunes@hotmail.com 

Thanks!

**Comment by songzheng112009** [comment]
Could you please send me the SCARED dataset. I tried to send the challenge rule to Allen, but there is no response. My email is 1120099373sz@gmail.com. Thank you!

**Comment by yanzhou-li** [comment]
你好，李yanzhou已经收到你的邮件，谢谢！

**Comment by songzheng112009** [comment]
> Hello,
> 
> Thank you for your work. I recently have access to the SCARED dataset, after contacting the organizers. I am trying to understand your data loader for this dataset but I cannot seem to reconcile the data structure from the files I have downloaded with your code.
> 
> I have datasets 1 - 9, and within each keyframes 1-5. Within each keyframe, there's a 'data' folder with frame_data and scene_points sub-folders. One level up, there is a YAML file, left and right depth maps and then right and left images.
> 
> Are you familiar with this data format?
> 
> Thank

Could you please send me the SCARED dataset. I tried to send the challenge rule to Allen, but there is no response. My email is [1120099373sz@gmail.com](mailto:1120099373sz@gmail.com). Thank you!

**Comment by herorhy** [comment]
Could you please send me the SCARED dataset. I tried to send the challenge rule to Allen, but there is no response. My email is renhuayang@163.com. Thank you!

**Comment by myriam-mrch** [comment]
Hello @yanzhou-li, 
Could you please send me a link with the SCARED dataset, thank you very much ! 
myriam.mrch1@gmail.com

**Comment by chyang0822** [comment]
> > 你好，   你好,
> > 感谢您的工作。在联系组织者后，我最近可以访问 SCARED 数据集。我正在尝试了解您为此数据集提供的数据加载器，但我似乎无法将我下载的文件中的数据结构与您的代码进行协调。谢谢你的工作。在与组织者联系后，我最近可以访问SCARED数据集。我试图了解这个数据集的数据加载器，但我似乎无法从我下载的文件与你的代码调和数据结构。
> > 我有数据集 1 - 9，每个关键帧内有 1-5。每个关键帧内都有一个“数据”文件夹，其中包含 frame_data 和 scene_points 子文件夹。上一层有一个 YAML 文件、左右深度图以及左右图像。我有数据集1- 9，并在每个关键帧1-5。在每个关键帧中，都有一个带有frame_data和scene_points子文件夹的“data”文件夹。再往上一层，有一个YAML文件，左右深度图，然后是左右图像。
> > 您熟悉这种数据格式吗？您熟悉这种数据格式吗?
> > 感谢   谢谢
> 
> @PrinceEAdjei,你好，你能分享一下 SCARED 数据集吗？如果可以，请通过[cd_freya@163.com](mailto:cd_freya@163.com)与我联系。 谢谢！！！！！！



> > Hello,
> > Thank you for your work. I recently have access to the SCARED dataset, after contacting the organizers. I am trying to understand your data loader for this dataset but I cannot seem to reconcile the data structure from the files I have downloaded with your code.
> > I have datasets 1 - 9, and within each keyframes 1-5. Within each keyframe, there's a 'data' folder with frame_data and scene_points sub-folders. One level up, there is a YAML file, left and right depth maps and then right and left images.
> > Are you familiar with this data format?
> > Thank
> 
> Could you please send me the SCARED dataset. I tried to send the challenge rule to Allen, but there is no response. My email is [1120099373sz@gmail.com](mailto:1120099373sz@gmail.com). Thank you!

Could you please send me a link with the SCARED dataset, thank you very much ! My email is [270917365@qq.com](mailto:1120099373sz@gmail.com). Thank you!

**Comment by yanzhou-li** [comment]
你好，李yanzhou已经收到你的邮件，谢谢！

**Comment by chyang0822** [comment]
Can you provide the SCARED dataset to me through email ***@***.***) if you have it? Because I have been working on an endoscopic project and need it very badly, please.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mli0603/stereo-transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月29日(星期四) 上午10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mli0603/stereo-transformer] How to get the dataset SCARED? (#4)





 你好，李yanzhou已经收到你的邮件，谢谢！

**Comment by oDaiSuno** [comment]
> 你好，李yanzhou已经收到你的邮件，谢谢！

Could you please send me a link with the SCARED dataset, thank you very much ! My email is [sundai@ustc.edu] Thank you!

**Comment by yanzhou-li** [comment]
你好，李yanzhou已经收到你的邮件，谢谢！

**Comment by luoyu5023** [comment]
Could you please send me the SCARED dataset. My email is 22315023@zju.edu.cn. Thank you!

**Comment by yanzhou-li** [comment]
你好，李yanzhou已经收到你的邮件，谢谢！

**Comment by Yinheng-Lin** [comment]
Hi, I need the SCARED dataset for an endoscopy project, could you send me a copy of this dataset, I would appreciate it! My e-mail is 535045291@qq.com

> 你好，李彦洲已经收到你的邮件，谢谢！

**Comment by FD7717** [comment]
Hello @yanzhou-li 
Could you please send me the SCARED dataset? My email is [zhangjiawen0701@163.com](mailto:zhangjiawen0701@163.com). Thank you!

**Comment by oneway-phil** [comment]
求分享下SCARED数据集，我的邮箱wangweiw97@163.com,非常感谢

**Comment by oneway-phil** [comment]
Hello @yanzhou-li
求分享下SCARED数据集，我的邮箱[wangweiw97@163.com](mailto:wangweiw97@163.com),非常感谢

**Comment by AeroRim** [comment]
@yanzhou-li 。您好，请问您能分享一下SCARED数据集吗？我的邮箱是lsy1999wasd@126.com，Thank you!

**Comment by yanzhou-li** [comment]
你好，李yanzhou已经收到你的邮件，谢谢！

**Comment by JauJieYou** [comment]
@PrinceEAdjei @yanzhou-li 您好，请问您能分享一下SCARED数据集吗？我的邮箱是 [jaujie@gmail.com](mailto:jaujie@gmail.com). Thank you very much!

**Comment by yanzhou-li** [comment]
你好，李yanzhou已经收到你的邮件，谢谢！

**Comment by cgchrfchscyrh** [comment]
@yanzhou-li Hello, could you please send me the SCARED dataset? My email is liusongyang@ufl.edu. Thank you very much!

**Comment by yanzhou-li** [comment]
你好，李yanzhou已经收到你的邮件，谢谢！

**Comment by HahaOptimus2** [comment]
@yanzhou-li Hello, could you please send me the SCARED dataset? My email is tangzhongyuannn@gmail.com. Thank you very much!

**Comment by van-jiji** [comment]
@yanzhou-li Can you please share the SCARED dataset. If you can, contact me at 1206831464@qq.com.

**Comment by yanzhou-li** [comment]
你好，李yanzhou已经收到你的邮件，谢谢！

**Comment by Eira333** [comment]
Hello @yanzhou-li
Could you please send me the SCARED dataset? My email is eiray886@gmail.com  Thank you!

**Comment by yanzhou-li** [comment]
你好，李yanzhou已经收到你的邮件，谢谢！

**Comment by Eira333** [comment]
@PrinceEAdjei @yanzhou-li 您好，请问您能分享一下SCARED数据集吗？我的邮箱是  eiray886@gmail.com  Thank you very much!
Could you please send me the SCARED dataset? My email is [eiray886@gmail.com]Thank you!
