### ISSUE TITLE
RuntimeError: running_mean must be defined in evaluation mode

### ISSUE THREAD

**Issue by rebecca0011** [mli0603/stereo-transformer#57]
I run the lastest code. The code stopped after only 1 epoch (parameter :epoch 10) and got this error. Could you please give me some advise?
`RR loss 18242.66715580225
  0%|                                                                                                                                                    | 0/4248 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 250, in <module>
    main(args_)
  File "main.py", line 236, in main
    eval_stats = evaluate(model, criterion, data_loader_val, device, epoch, summary_writer, False)
  File "/home/rc/anaconda3/envs/DL/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/rc/StereoMatching/stereo-transformer-1/utilities/eval.py", line 35, in evaluate
    outputs, losses, sampled_disp = forward_pass(model, data, device, criterion, eval_stats, idx, logger)
  File "/home/rc/StereoMatching/stereo-transformer-1/utilities/foward_pass.py", line 55, in forward_pass
    outputs = model(inputs)
  File "/home/rc/anaconda3/envs/DL/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/rc/StereoMatching/stereo-transformer-1/module/sttr.py", line 82, in forward
    feat = self.backbone(x)  # concatenate left and right along the dim=0
  File "/home/rc/anaconda3/envs/DL/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/rc/StereoMatching/stereo-transformer-1/module/feat_extractor_backbone.py", line 84, in forward
    output = self.in_conv(src_stereo)  # 1/2
  File "/home/rc/anaconda3/envs/DL/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/rc/anaconda3/envs/DL/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/rc/anaconda3/envs/DL/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/rc/anaconda3/envs/DL/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 140, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/home/rc/anaconda3/envs/DL/lib/python3.7/site-packages/torch/nn/functional.py", line 2147, in batch_norm
    input, weight, bias, running_mean, running_var, training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: running_mean must be defined in evaluation mode
`

**Comment by mli0603** [comment]
Thanks @rebecca0011, looking into this now.

**Comment by mli0603** [comment]
Hi @rebecca0011 

Can you confirm you are running the latest code? From the error log, it is saying that L236 is calling "evaluate" but it is [L241](https://github.com/mli0603/stereo-transformer/blob/sttr-light/main.py#L241) in the github code. Before I dive deep, I want to make sure we have the same code.

**Comment by rebecca0011** [comment]
I am using two days ago cloned code.I just compared the code of "main.py" and "module / sttr.py", showing the code I used and the lastest code.

**Comment by mli0603** [comment]
@rebecca0011 
What is your torch version?

**Comment by rebecca0011** [comment]
> @rebecca0011 What is your torch version?

Nvidia gtx 3090
Cuda 11.2
Python 3.7
Pytorch 1.8.0

**Comment by mli0603** [comment]
@rebecca0011 

Are you using Apex?

**Comment by rebecca0011** [comment]
> @rebecca0011
> 
> Are you using Apex?

I successfully installed Apex，but I use the command in README，so I do not use

**Comment by mli0603** [comment]
Thanks.

The exception is thrown at [this line in pytorch](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Normalization.cpp#L449). I tried to replicate what you have with the following torch version
```
# CUDA 11.1
conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=11.1 -c pytorch -c conda-forge
```
But I still haven't been able to reproduce the error you have so far.

Would you mind trying the following?
- cloning the latest code: let's just make sure you have the right code from master branch.
- trying inferencing directly: As this error is thrown during evaluate, maybe we can pin down what is wrong more directly by inferencing.

**Comment by rebecca0011** [comment]
> Thanks.
> 
> The exception is thrown at [this line in pytorch](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Normalization.cpp#L449). I tried to replicate what you have with the following torch version
> 
> ```
> # CUDA 11.1
> conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=11.1 -c pytorch -c conda-forge
> ```
> 
> But I still haven't been able to reproduce the error you have so far.
> 
> Would you mind trying the following?
> 
>     * cloning the latest code: let's just make sure you have the right code from master branch.
> 
>     * trying inferencing directly: As this error is thrown during evaluate, maybe we can pin down what is wrong more directly by inferencing.

OK！Thanks a lot！ 
I am trying to compare the performance of STTR and Raft-Stereo, so I wanted to train with the fixed parameters and then compare the results with the EPE and NPE on the test dataset.
I am now trying to use Apex for training to see if I can succeed.
I will clone the latest code，or try inferencing directly pin down what is wrong tomorrow.
Thx again!

**Comment by rebecca0011** [comment]
I changed another computer to do the training job and success.
Thanks!!!!!!!!
