### ISSUE TITLE
Cuda out of memory

### ISSUE THREAD

**Issue by chaimaOues** [mli0603/stereo-transformer#67]
Hello, when i run the code in google colab it works very well but when i tried to run it in my personal pc  i get in '  output = model(input_data)' this error:
RuntimeError: CUDA out of memory. Tried to allocate 1.28 GiB (GPU 0; 4.00 GiB total capacity; 1.07 GiB already allocated; 797.70 MiB free; 1.74 GiB reserved in total by PyTorch)

i tried every solution in the web but always the same error ,can someone help me please
PS: i have cuda in my pc

**Comment by mli0603** [comment]
Hi @chaimaOues 

It looks like untorunately 4GB may not be enough to run your images. If you are using sttr-light already, maybe you can downsample the images to lower resolution.
