### ISSUE TITLE
disparity in the left figure is all 0

### ISSUE THREAD

**Issue by yszhuu** [mli0603/stereo-transformer#78]
hi. disparity in the left figure is all negative. When executing evaluate in eval.py on SceneFlowFlyingThingsDataset,   torch.all(invalid_mask)  is True which cause valid_samples in eval.py is 0.  eval_stats['epe'] = eval_stats['epe'] / valid_samples  in  eval.py report error.

**Comment by mli0603** [comment]
I think you have downloaded the wrong scene flow dataset. The other dataset uses inverse disparity and their disparity is all negative. Can you check if this is the case?

**Comment by yszhuu** [comment]
Thank you very much. Sorry to bother you, I have another question.  


> I think you have downloaded the wrong scene flow dataset. The other dataset uses inverse disparity and their disparity is all negative. Can you check if this is the case?

Thank you very much. Sorry to bother you, I have another question.  Which dataset of FlyingThings3D subset, FlyingThings3D and Scene Flow (including FlyingThings3D, Driving, Monkaa) is used in Table 1 in the paper.


> I think you have downloaded the wrong scene flow dataset. The other dataset uses inverse disparity and their disparity is all negative. Can you check if this is the case?

Thank you very much. Sorry to bother you, I have another question.  Which dataset of FlyingThings3D subset, FlyingThings3D and Scene Flow (including FlyingThings3D, Driving, Monkaa) is used in Table 1 in the paper.

**Comment by yszhuu** [comment]
> I think you have downloaded the wrong scene flow dataset. The other dataset uses inverse disparity and their disparity is all negative. Can you check if this is the case?

Thank you very much. Excuse me, I have another question. Which of the FlyingThings3D subset, FlyingThings3D, Scene Flow Datasets (including FlyingThings3D, Driving, Monkaa) datasets is used for the result in table 1 in the paper .
