### ISSUE TITLE
'_pygit2.GitError'

### ISSUE THREAD

**Issue by 953390337** [mli0603/stereo-transformer#79]
When we debug the project, it  occurs GitError('Repository not found at .',) in L41 in checkpoint_saver.py . what should we do?

**Comment by mli0603** [comment]
You probably have downloaded the code. Clone it instead and the error will be gone.

**Comment by 953390337** [comment]
Dear Authors:
When we run the inference.py, the results are saved in a dat file. We tried some ways to get it to visualize, but it didn't work out. Could you tell me what should we do? Thank you!
