### ISSUE TITLE
Unable to use `nn.DataParallel()` for multi-GPU training

### ISSUE THREAD

**Issue by saveleaf** [mli0603/stereo-transformer#87]
Hello, thank you very much for your outstanding work, but I have a very puzzling question.
When I wanted to try multi-GPU parallel training, I used the following code as usual: `model = nn.DataParallel(model)` but I found that the runtime didn't find to get the expected results, can you please ask me if there's any particular reason for this?

**Comment by mli0603** [comment]
Hi @saveleaf 

Thank you for your interest in the project.

When I wrote the code, I only had one GPU and did not configure the code such that it supports parallel training. It may require some code changes to make it work. Feel free to submit a PR if you make it work!

**Comment by XiandaGuo** [comment]
We have seamlessly integrated the contributions of the talented author, STTR, into OpenStereo(https://github.com/XiandaGuo/OpenStereo), enabling support for multi-GPU training. We invite you to explore and experience it firsthand!
