### ISSUE TITLE
Is it possible to evaluate/finetune the model with batchsize > 1 case?

### ISSUE THREAD

**Issue by MinJunKang** [mli0603/stereo-transformer#9]
Hello, thanks for your great work!

All the examples you've provide seems to work with batchsize 1 as default.

I tried to change the value of batchsize >= 2 and evaluate/finetune the model but the following error happens at this line (utilities/train.py at line 30).

Code : 
![image](https://user-images.githubusercontent.com/29685163/103390675-1ae01e00-4b59-11eb-8f32-cd5d80cc0021.png)

Error : 
![image](https://user-images.githubusercontent.com/29685163/103390684-29c6d080-4b59-11eb-925d-d1d994d785a7.png)

It seems that each data in the same batch has different shape so we cannot combine them into one tensor for more than 2 batch case.

Could you help me to run with the batchsize >= 2? I just want to see how transformer works with this case. 

Thanks!

**Comment by mli0603** [comment]
Hi @MinJunKang, yes you are right, I trained everything with batch size equal to 1, so I didn't have problems with random cropping.

You should be able to run with larger batch by just removing random cropping or replacing with fixed size cropping [here](https://github.com/mli0603/stereo-transformer/blob/main/dataset/scene_flow.py#L146). However, you may run into bugs since I have never tried batch size larger than 1. If you see a bug let me know ;)

**Comment by JYJ-YeongJoon-Jang** [comment]
Thanks for your kind reply!

It seems that there is some issue running the model with batch size larger than 1 at positional encoder function and transformer function. 

Now I will close this issue and I will let you know if there is some progress that can update these functions to be worked with more than batchsize 2 by opening new issue.

Again, thanks for your reply! It helps me a lot :)

**Comment by MinJunKang** [comment]
Hi! @mli0603 Thanks for your kind reply!

It seems that there is some issue running the model with batch size larger than 1 at positional encoder function and transformer function.

Now I will close this issue and I will let you know if there is some progress that can update these functions to be worked with more than batchsize 2 by opening new issue.

Again, thanks for your reply! It helps me a lot :)

**Comment by mli0603** [comment]
Sounds good. Feel free to submit a pull request if you manage to fix it ;)
